export const cardsData = [
    {
        label: "Mlops",
        volume: "49.5K",
        growth: "+99X+",
        description: "Machine learning operations. A set of best practices in the machine learning development cycle.",
        isPro: false,
        id: "mlops",
        trend: 'up',
      },
      {
        label: "Sea moss gummies",
        volume: "12.1K",
        growth: "+99X+",
        description: "Vitamin supplements that are intended to promote thyroid health and weight loss.",
        isPro: false,
        id: "sea-moss-gummies",
        // trend: 'up',
      },
      {
        label: "Ai logo generator",
        volume: "450K",
        growth: "+99X+",
        description: "A software tool that uses artificial intelligence to generate custom logos for individuals and businesses, allowing them to quickly and easily create a unique brand identity.",
        isPro: false,
        id: "ai-logo-generator",
        trend: 'down',
      },
      {
        label: "Ai image enhancer",
        volume: "110K",
        growth: "+99X+",
        description: "Image modification software that improves image resolution, color, and detail.",
        isPro: false,
        id: "ai-image-enhancer",
        trend: 'down',
      },
      {
        label: "Data lakehouse",
        volume: "9.9K",
        growth: "+99X+",
        description: "Data solution concept combining 'data warehouse' and 'data lake'.",
        isPro: false,
        id: "data-lakehouse",
        trend: 'up',
      },
      {
        label: "Loop earplugs",
        volume: "550K",
        growth: "+9800%",
        description: "Earplugs that are designed to be more comfortable and effective than traditional earplugs, often using a loop or other design to fit more securely in the ear.",
        isPro: false,
        id: "loop-earplugs",
      },
      {
        label: "Prebiotic soda",
        volume: "12.1K",
        growth: "+9700%",
        description: "Carbonated beverage containing compounds that stimulate gut bacteria growth.",
        isPro: false,
        id: "prebiotic-soda",
      },
      {
        label: "Cold plunge tub",
        volume: "135K",
        growth: "+9200%",
        description: "A small, shallow tub or pool filled with cold water, often used for hydrotherapy or recovery after exercise.",
        isPro: false,
        id: "cold-plunge-tub",
      },
      {
        label: "Qfbbcfdces",
        volume: "27.1K",
        growth: "+9000%",
        description: "Adfbacdy tcct iceafecs mecfdg on fdbr lbbc, sbcbber to hdw an aeffbl wdecc. It hbeds idcfffe bceacba, rfafe of aebeaeeb, acd eceedccas cfbe mfdafec, ufebr ldcb, aed accb. Tefde aae deefcffat teads of Qdcbdaafbs ebeebdddf, iccaceeag wfcecag acd tcbedbee.",
        isPro: true,
        id: "qfbbcfdces",
        trend: 'up',
      },
      {
        label: "Spacegoods",
        volume: "8.1K",
        growth: "+8300%",
        description: "Space Goods makes a mushroom-based supplement powder to increase your focus, creativity, and mood.",
        isPro: false,
        id: "spacegoods",
      },
      {
        label: "Temu",
        volume: "24.9M",
        growth: "+8000%",
        description: "Shopping app that aims to challenge popular retailers like Shein and Amazon. It has been experiencing significant growth but has raised concerns about safety, security, and legal issues. Potential users should exercise caution and thoroughly research before using Temu.",
        isPro: false,
        id: "temu",
      },
      {
        label: "Prompt engineering",
        volume: "165K",
        growth: "+5700%",
        description: "Prompt engineering is a technique used in artificial intelligence (AI), specifically in natural language processing (NLP). In prompt engineering, the description of a task is included in the input as a question, rather than being implied. This allows for a more explicit and accurate understanding of the task, improving the performance of the AI system.",
        isPro: false,
        id: "prompt-engineering",
        trend: 'up',
      },
      {
        label: "Writesonic",
        volume: "246K",
        growth: "+5500%",
        description: "Writesonic is an AI writer that creates SEO-friendly content for blogs, Facebook ads, Google ads, and Shopify for free.",
        isPro: false,
        id: "writesonic",
      },
      {
        label: "Walking pad",
        volume: "450K",
        growth: "+4350%",
        description: "A treadmill or other device designed for use in a standing or walking position.",
        isPro: false,
        id: "walking-pad",
      },
      {
        label: "Fractional CTO",
        volume: "2.9K",
        growth: "+3300%",
        description: "Chief technology officer hired on a very part-time basis. This gives lower-budget businesses access to senior executives.",
        isPro: false,
        id: "fractional-cto",
      },
      {
        label: "Typebot",
        volume: "22.2K",
        growth: "+3200%",
        description: "Software platform facilitating automated conversations for businesses.",
        isPro: false,
        id: "typebot",
      },
      {
        label: "Wfbadaee bfcbat pebp",
        volume: "33.1K",
        growth: "+2400%",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero non libero laboriosam expedita porro atque accusamus neque dignissimos maxime doloremque.",
        isPro: true,
        id: "wfbadaee-bfcbat-pebp",
      },
      {
        label: "Hbeafeccn sfdefaat reaan",
        volume: "6.6K",
        growth: "+2300%",
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis molestiae magni iure fugiat exercitationem impedit illum. Accusantium saepe dolores magni laboriosam, dolore officiis adipisci fugit exercitationem esse modi eveniet blanditiis omnis, qui ut perspiciatis.",
        isPro: true,
        id: "hbeafeccn-sfdefaat-reaan",
      },
      {
        label: "wolf haircut",
        volume: "110K",
        growth: "+2100%",
        description: "Tousled, fierce, textured, and slightly wild hairstyle characterized by layers, suitable for various face shapes. Adds volume and texture to the hair, giving it a bold and edgy appearance. Popular among both men and women.",
        isPro: false,
        id: "wolf-haircut",
      },
      {
        label: "Abaeds",
        volume: "90.5K",
        growth: "+1900%",
        description: "AfbedS is an effdbeeece aeebedfacn pfcbdccm tfdt uabs AI to habp sedcfbs oddeefce taedr ofcafe scdeb. It ofbeds fbefcfds ldfe pbcffdt rcaffdcc, ieaedcbcy maebbebfad, acd abcbdeced pafebag to hfap safebfs scbffbbefe teedr eedaedfefe ocaceceffc. undefinedfcddaecfeafabdcbecabaabcbfddcbffeundefined",
        isPro: true,
        id: "abaeds",
      },
      {
        label: "Febbes",
        volume: "22.2K",
        growth: "+1900%",
        description: "AdfacffeffcccafdccbcccaA fecfcdddk far mccccdag cbccafbdfad oadfdbcdg eebdccbefefe.",
        isPro: true,
        id: "febbes",
      },
      {
        label: "Discoloration serum",
        volume: "5.4K",
        growth: "+1675%",
        description: "Skincare products that treat hyperpigmentation and uneven skin tone.",
        isPro: false,
        id: "discoloration-serum",
        trend:'down'
      },
      {
        label: "Artgrid",
        volume: "40.5K",
        growth: "+1600%",
        description: "Subscription-based stock footage library. Users can access a wide array of high-resolution clips.",
        isPro: false,
        id: "artgrid",
      },
      {
        label: "Preply",
        volume: "550K",
        growth: "+1567%",
        description: "Online foreign-language tutoring marketplace.",
        isPro: false,
        id: "preply",
      },
      {
        label: "Bbfddo pbefcfs",
        volume: "40.5K",
        growth: "+1517%",
        description: "Obfacdc bcffdedefcdd sdabaebdf, kcaen fcr bcebg hecfaaacaedabd, mbcafcee waeeeda, cabafdg add sbfcy sced. Bdeddo is acco abedffbceedbacddfdefbaafaaffcdbea sbbadbadcde mbfcfael wdbch mbfbs bbadeo pffcbbs an efbfefbcbfby cdbded.",
        isPro: true,
        id: "bbfddo-pbefcfs",
      },
      {
        label: "Members Only",
        volume: "110K",
        growth: "+1150%",
        description: "Scbfaaccfs pddbdedead paaabe uebd to pbay tfe rddbft sffed, Pffdc.",
        isPro: true,
        id: "members-only",
      },
      {
        label: "Lions Mane Supplement",
        volume: "22.2K",
        growth: "+1011%",
        description: "Lion's mane (Hericium erinaceus) mushrooms contain many plant compounds that may have health benefits including: Antioxidants, Antidiabetic, Anticancer, Anti-inflammatory, Antimicrobial, Antihyperglycemic, Hypolipidemic.",
        isPro: false,
        id: "lions-mane-supplement",
      },
      {
        label: "Draft AI",
        volume: "880",
        growth: "+988%",
        description: "Draft AI is a tool that can create written and visual content quickly. It uses AI to generate content.",
        isPro: false,
        id: "draft-ai",
      },
      {
        label: "Magnesium glycinate",
        volume: "823K",
        growth: "+889%",
        description: "Form of magnesium combined with the amino acid glycine, commonly used as a dietary supplement to support various bodily functions.",
        isPro: false,
        id: "magnesium-glycinate",
      },
      {
        label: "Evtol",
        volume: "40.5K",
        growth: "+870%",
        description: 'eVTOL stands for "electric vertical take-off and landing". As aircraft, they are typically designed for a small number of passengers and short flights.',
        isPro: false,
        id: "evtol",
      }
];